### ISSUE TITLE
Replace Placeholders with Environmental variables 

### ISSUE THREAD

**Issue by alienden** [Threekit/threekit-react-development-kit#9]
Replace Placeholders with Environmental variables. Update README to reflect new setup

https://github.com/Threekit/threekit-react-development-kit/blob/8bf2ee815f1dcffb74e46e2c67e3f69f346604e1/src/demo-project/index.js#L6-L9

**Comment by asaeed2** [comment]
Feature implemented with path to env file should be `./.env`.
